## Variables

In [2]:
a = 10
v = 100

print(a + v)

110


### Listas, tuplas y diccionarios

In [4]:
l = ['a', 3, 8.32, [1, 2, 3]]
l

['a', 3, 8.32, [1, 2, 3]]

In [6]:
len(l)

4

In [7]:
print(l[0], l[3])

a [1, 2, 3]


In [8]:
l.append(4)

In [9]:
print(l)

['a', 3, 8.32, [1, 2, 3], 4]


In [11]:
t = (1, 2)
print(t)

(1, 2)


In [13]:
#Tuplas son inmutables
t[2] = 3
print(t)

TypeError: 'tuple' object does not support item assignment

In [15]:
d = {"est1": "Laura", 2: 3}
d

{'est1': 'Laura', 2: 3}

In [16]:
print(d["est1"], d[2])

Laura 3


## Flujos de control

In [17]:
a = 50
if a in l:
    print("A en L")
else:
    print("A no en L")

A no en L


In [18]:
for n in l:
    print(n)

n = 0
while n < 11:
    print(n)
    n += 1

a
3
8.32
[1, 2, 3]
4
0
1
2
3
4
5
6
7
8
9
10


## Numpy

### Arreglos

In [19]:
import numpy as np

In [24]:
a = np.array([1, 2, -3, 300], dtype='uint')
b = np.array([1, 2, -3, 300], dtype='complex')
print(a)
print(a.dtype)

print(b)

[                   1                    2 18446744073709551613
                  300]
uint64
[   1.+0.j    2.+0.j   -3.+0.j  300.+0.j]


In [27]:
g = np.ones((10, 10))
print(g)
print(g.dtype)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
float64


In [29]:
g[1, 0: 3] = 4
print(g)

[[ 4.  4.  4.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  4.  4.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### Aritmética

In [32]:
f = np.zeros((10, 10)) + 3
print(f)

[[ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]]


In [33]:
print(f * g)

[[ 12.  12.  12.   3.   3.   3.   3.   3.   3.   3.]
 [ 12.  12.  12.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]
 [  3.   3.   3.   3.   3.   3.   3.   3.   3.   3.]]


### Referencias vistas y copias

In [36]:
#Referencia
f = g

f[4, 5] = 77
print(f)
print(g)

[[  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.  77.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[[  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.  77.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1

In [38]:
f = g.copy()
f[3, 4] = -1000
print(f)
print(g)

[[    4.     4.     4.     1.     1.     1.     1.     1.     1.     1.]
 [    4.     4.     4.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1. -1000.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.    77.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]
 [    1.     1.     1.     1.     1.     1.     1.     1.     1.     1.]]
[[  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  4.   4.   4.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.  77.   1.   1.   1.   1.]
 [  

## Histograma

In [44]:
from skimage import data
from numba import jit
import matplotlib.pyplot as plt

def histograma(g):
    h = np.zeros(256, dtype='int')
    M, N = g.shape
    
    for n in range(N):
        for m in range(M):
            h[g[m, n]] += 1
            
    return h

g = data.camera()
%matplotlib inline
plt.imshow(g, cmap = cm.gray)

NameError: name 'cm' is not defined

In [46]:
h = histograma(g)
plt.imshow(h)

NameError: name 'zeros' is not defined